import xml.etree.ElementTree as ET
from xml.dom import minidom

def write_resx(path, data):
    root = ET.Element("root")
    for name, val in [
        ("resmimetype", "text/microsoft-resx"),
        ("version", "2.0"),
        ("reader", "System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"),
        ("writer", "System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"),
    ]:
        h = ET.SubElement(root, "resheader", {"name": name})
        v = ET.SubElement(h, "value")
        v.text = val
    for k, v in sorted(data.items()):
        d = ET.SubElement(root, "data", {"name": k, "{http://www.w3.org/XML/1998/namespace}space": "preserve"})
        val = ET.SubElement(d, "value")
        val.text = v
    xml = ET.tostring(root, encoding="unicode")
    doc = minidom.parseString(xml)
    with open(path, "w", encoding="utf-8") as f:
        f.write('<?xml version="1.0" encoding="utf-8"?>\n')
        doc.documentElement.writexml(f, indent="  ", addindent="  ", newl="\n")

# 欢迎各路大佬 纠正/添加 翻译（
zh = {
    "App_Title_ControlPanel": "BASpark - 控制面板",
    "App_AlreadyRunning": "BASpark 已经在运行中，请检查系统托盘。",
    "App_AlreadyRunning_Title": "提示",
    "Tray_Text": "BASpark - 点击特效",
    "Tray_OpenPanel": "打开控制面板",
    "Tray_Restart": "重启应用",
    "Tray_Exit": "彻底退出",
    "Tray_RestartFailed": "重启失败: {0}",
    "WebView2_InitFailed": "WebView2 初始化失败: {0}",
    "LangSelect_Title": "选择语言",
    "LangSelect_Subtitle": "请选择界面显示语言。选择后可在设置中随时更改。",
    "LangSelect_Chinese": "简体中文",
    "LangSelect_English": "English",
    "LangSelect_Japanese": "日本語",
    "LangSelect_Continue": "继续",
    "Privacy_Title": "欢迎使用 BASpark",
    "Privacy_Intro": "在使用本软件前，请详细阅读以下内容：",
    "Privacy_OpenSource_Title": "● 开源声明",
    "Privacy_OpenSource_Body": "本软件完全开源且免费。严禁商业倒卖，若您是付费取得，请立即向平台举报并申请退款。",
    "Privacy_Security_Title": "● 安全预警 (重要)",
    "Privacy_Security_Body": "请确保从官方渠道下载。第三方渠道提供的版本可能存在被篡改或报毒的风险。",
    "Privacy_Privacy_Title": "● 隐私保障",
    "Privacy_Privacy_Body": "绝不收集您的按键内容、文件或任何私密信息。所有特效渲染均在本地完成。",
    "Privacy_Telemetry": "同意加入用户体验改进计划 (匿名统计)",
    "Privacy_Refuse": "拒绝并退出",
    "Privacy_Agree": "同意并进入",
    "Privacy_Tagline": "Sensei, welcome back to Schale.",
    "Privacy_VersionFailed": "版本信息读取失败",
    "Nav_Home": "首页",
    "Nav_Settings": "设置",
    "Nav_Basic": "基础设置",
    "Nav_Visual": "视觉表现",
    "Nav_Filter": "环境过滤",
    "Nav_MultiScreen": "多屏管理",
    "Nav_About": "关于",
    "Welcome_NoticeLoading": "加载中...",
    "Welcome_Title": "欢迎回来，老师！",
    "Welcome_Subtitle": "Sensei, welcome back!",
    "Welcome_StatsTitle": "实时统计",
    "Welcome_StatusLabel": "当前状态:",
    "Welcome_ClicksLabel": "累计点击次数:",
    "Welcome_ClicksUnit": "{0} 次",
    "Status_Paused": "已暂停",
    "Status_Filtered": "环境过滤中",
    "Status_Active": "工作中",
    "Status_AdminPending": "管理员模式将在保存并重启后生效",
    "Settings_Title": "参数配置",
    "Settings_ApplyHint": "*修改设置后，请点击右侧 [应用更改] 按钮生效。",
    "Settings_Apply": "应用更改",
    "Basic_Title": "基础设置",
    "Basic_Language": "界面语言",
    "Basic_MasterSwitch": "启用鼠标点击特效",
    "Basic_TrailSwitch": "启用鼠标常驻拖尾",
    "Basic_ScrollbarVisibility": "滚动条显示",
    "Basic_ScrollbarAlways": "常驻显示",
    "Basic_ScrollbarOnScroll": "仅滚动时显示",
    "Basic_ScrollbarHint": "* 控制面板滚动条较细；仅滚动时显示可减少调整窗口大小时滚动条反复出现/消失的视觉割裂。",
    "Basic_ClickType": "触发按键类型",
    "Basic_LeftClick": "仅左键",
    "Basic_RightClick": "仅右键",
    "Basic_BothClick": "左右键",
    "Basic_MiddleClick": "鼠标中键按下时触发特效",
    "Basic_ScreenshotMode": "截图兼容模式",
    "Basic_ScreenshotHint": "* (实验性功能) 开启后截图画面将不包含特效：检测到系统截图界面或 QQ 默认截图快捷键时会短暂隐藏叠加层以便框选窗口。",
    "Basic_AutoStart": "开机自动启动",
    "Basic_StartSilent": "静默启动 (最小化到托盘)",
    "Basic_RunAsAdmin": "以管理员权限运行程序",
    "Basic_RunAsAdminHint": "* 若需在任务管理器等部分高权限窗口显示特效，请勾选此项。",
    "Basic_Touchscreen": "触摸屏模式",
    "Basic_TouchscreenHint": "* 开启后，即便系统隐藏了鼠标指针特效依然生效，仅适用于触摸屏或特定的全屏应用环境。",
    "Basic_Telemetry": "允许发送匿名运行数据以改进软件",
    "Visual_Title": "视觉表现",
    "Visual_ResetDefaults": "恢复默认设置",
    "Visual_InputHint": "提示：可点击数字输入精确值后可按回车应用",
    "Visual_Scale": "缩放比例",
    "Visual_Opacity": "全局不透明度",
    "Visual_LinkedSpeed": "拖尾与点击使用同一动画速度",
    "Visual_LinkedSpeedHint": "关闭此项后可单独加快或减慢拖尾衰减与移动粒子，而不影响点击波纹与爆发粒子，与下方「拖尾刷新率」不同。",
    "Visual_AnimSpeed": "动画播放速度",
    "Visual_TrailAnimSpeed": "拖尾动画速度",
    "Visual_ClickAnimSpeed": "点击动画速度",
    "Visual_TrailRefresh": "拖尾刷新率",
    "Visual_Color": "特效主题颜色",
    "Visual_ChangeColor": "更改颜色",
    "Filter_Title": "环境过滤",
    "Filter_Enable": "启用智能环境探测",
    "Filter_Fullscreen": "全屏应用前台运行时自动暂停",
    "Filter_Desktop": "在桌面上显示特效",
    "Filter_Profiles": "配置组管理",
    "Filter_Delete": "删除",
    "Filter_Rename": "重命名",
    "Filter_New": "新建",
    "Filter_Mode": "过滤模式",
    "Filter_Mode_Disabled": "🚫 关闭过滤",
    "Filter_Mode_Blacklist": "❌ 黑名单模式",
    "Filter_Mode_Whitelist": "✅ 白名单模式",
    "Filter_ProcessList": "已配置进程列表",
    "Filter_Remove": "移除",
    "Filter_AddProcess": "添加进程",
    "Filter_Add": "添加",
    "Filter_Browse": "浏览...",
    "Filter_SelectRunning": "从运行中选择",
    "MultiScreen_Title": "多屏显示管理",
    "MultiScreen_Refresh": "刷新显示器",
    "MultiScreen_Hint": "勾选要启用特效窗口的显示器。设置会按显示器名称和硬件 ID 记忆，显示屏变更后自动恢复。",
    "MultiScreen_Enable": "启用",
    "MultiScreen_Primary": " (主显示器)",
    "MultiScreen_Scale": "缩放 {0}%",
    "MultiScreen_Detail": "{0}  ·  位置 ({1}, {2})  ·  {3}",
    "About_Title": "关于",
    "About_CheckUpdate": "检查更新",
    "About_CheckingUpdate": "正在检查...",
    "About_Description": "深度复刻《蔚蓝档案》UI 风格动效的鼠标特效工具",
    "About_SecurityWarning": "安全提示：请务必确保从官方渠道下载。第三方分发渠道的版本可能存在报毒风险或恶意篡改。",
    "About_Support": "如果你喜欢本应用，欢迎支持开发者持续维护 ☕",
    "About_OfficialSite": "🌐 访问官方网站",
    "About_Github": "🌐 访问 GitHub 官方仓库",
    "About_Bilibili": "📺 关注 B 站官号",
    "About_QQ": "💬 加入 QQ 交流群",
    "About_Sponsor": "☕ 赞助支持作者",
    "About_Discord": "💬 加入 Discord 社区",
    "About_DevOptions": "开发者选项",
    "About_ResetAll": "重置所有设置并退出",
    "Overlay_RunningProcess": "从运行中进程添加",
    "Overlay_Cancel": "取消",
    "Overlay_ConfirmAdd": "确认添加",
    "Overlay_VisualReset": "选择要恢复默认的视觉表现项",
    "Overlay_ConfirmReset": "确认重置",
    "Overlay_RenameProfile": "重命名配置组",
    "Overlay_RenamePrompt": "请输入新的配置组名称：",
    "Overlay_ConfirmRename": "确认修改",
    "Msg_UpdateAvailable": "发现新版本: V{0}\n\n更新内容:\n{1}\n\n是否立即前往下载？",
    "Msg_UpdateAvailable_Title": "发现新版本",
    "Msg_UpToDate": "当前已是最新版本，无需更新！",
    "Msg_CheckUpdate_Title": "检查更新",
    "Msg_CheckUpdateFailed": "检查更新失败: \n{0}",
    "Msg_NetworkError": "网络错误",
    "Msg_NoUpdateNotes": "无更新说明",
    "Msg_DefaultNoticeTitle": "官方公告",
    "Msg_OpenLinkFailed": "无法打开链接: {0}",
    "Msg_KeepOneProfile": "至少需要保留一个配置组。",
    "Msg_Info": "提示",
    "Msg_ConfirmDeleteProfile": "确定要删除 '{0}' 吗？",
    "Msg_ConfirmDelete_Title": "确认删除",
    "Msg_SelectVisualReset": "请至少选择一项要恢复的内容。",
    "Msg_VisualReset_Title": "恢复默认设置",
    "Msg_VisualResetDone": "所选视觉表现项已恢复为默认值并已保存。",
    "Msg_MinOneScreen": "至少需要启用一个屏幕。",
    "Msg_MultiScreen_Title": "多屏控制",
    "Msg_AdminRestart": "需要以管理员权限重启应用以应用设置，是否立即重启？",
    "Msg_AdminRestart_Title": "需要权限",
    "Msg_SettingsApplied": "配置已成功应用！",
    "Msg_RestartAdminFailed": "提权重启失败，请尝试手动右键以管理员身份运行。\n错误信息: {0}",
    "Msg_Error": "错误",
    "Msg_ConfirmReset": "确定要重置所有配置吗？这将会清空所有配置，程序随后将关闭。",
    "Msg_ConfirmReset_Title": "确认重置",
    "Msg_DeleteFailed": "删除失败: {0}",
    "Msg_LanguageRestart": "界面语言已更改。是否立即重启以完全应用？",
    "Msg_LanguageRestart_Title": "语言已更改",
    "Dialog_ExeFilter": "可执行文件 (*.exe)|*.exe",
    "Dialog_SelectProcess": "选择应用进程",
    "Profile_Default": "默认配置",
    "Profile_New": "新配置组",
    "Profile_NewNumbered": "新配置组 {0}",
    "VisualReset_Scale": "缩放比例",
    "VisualReset_Scale_Sub": "默认 1.50 ×",
    "VisualReset_Opacity": "全局不透明度",
    "VisualReset_Opacity_Sub": "默认 100 %",
    "VisualReset_UnifiedSpeed": "统一动画速度",
    "VisualReset_UnifiedSpeed_Sub": "开启「同一速度」并默认 1.00 ×",
    "VisualReset_TrailSpeed": "拖尾动画速度",
    "VisualReset_TrailSpeed_Sub": "独立项默认 1.00 ×",
    "VisualReset_ClickSpeed": "点击动画速度",
    "VisualReset_ClickSpeed_Sub": "独立项默认 1.00 ×",
    "VisualReset_TrailRefresh": "拖尾刷新率",
    "VisualReset_TrailRefresh_Sub": "默认 40 Hz",
    "VisualReset_Color": "特效主题颜色",
    "VisualReset_Color_Sub": "默认 RGB(45,175,255)",
    "Version_ReadFailed": "版本信息读取失败",
    "Link_Discord_Url": "https://discord.gg/sgZMdqhfZu",
}

en = dict(zh)
en.update({
    "App_Title_ControlPanel": "BASpark - Control Panel",
    "App_AlreadyRunning": "BASpark is already running. Check the system tray.",
    "App_AlreadyRunning_Title": "Notice",
    "Tray_Text": "BASpark - Click Effects",
    "Tray_OpenPanel": "Open Control Panel",
    "Tray_Restart": "Restart App",
    "Tray_Exit": "Exit Completely",
    "Tray_RestartFailed": "Restart failed: {0}",
    "WebView2_InitFailed": "WebView2 initialization failed: {0}",
    "LangSelect_Title": "Choose Language",
    "LangSelect_Subtitle": "Select the display language. You can change it later in Settings.",
    "LangSelect_Continue": "Continue",
    "Privacy_Title": "Welcome to BASpark",
    "Privacy_Intro": "Please read the following before using this software:",
    "Privacy_OpenSource_Title": "● Open Source",
    "Privacy_OpenSource_Body": "This software is free and open source. Reselling is prohibited. If you paid for it, report the seller and request a refund.",
    "Privacy_Security_Title": "● Security Warning (Important)",
    "Privacy_Security_Body": "Download only from official channels. Third-party builds may be tampered with or flagged as malware.",
    "Privacy_Privacy_Title": "● Privacy",
    "Privacy_Privacy_Body": "We never collect keystrokes, files, or private data. All effects render locally.",
    "Privacy_Telemetry": "Join the anonymous telemetry program to help improve the app",
    "Privacy_Refuse": "Decline and Exit",
    "Privacy_Agree": "Agree and Continue",
    "Privacy_Tagline": "Sensei, welcome back to Schale.",
    "Privacy_VersionFailed": "Failed to read version info",
    "Nav_Home": "Home",
    "Nav_Settings": "Settings",
    "Nav_Basic": "Basic",
    "Nav_Visual": "Visual",
    "Nav_Filter": "Environment",
    "Nav_MultiScreen": "Displays",
    "Nav_About": "About",
    "Welcome_NoticeLoading": "Loading...",
    "Welcome_Title": "Welcome back, Sensei!",
    "Welcome_Subtitle": "Sensei, welcome back!",
    "Welcome_StatsTitle": "Live Stats",
    "Welcome_StatusLabel": "Status:",
    "Welcome_ClicksLabel": "Total clicks:",
    "Welcome_ClicksUnit": "{0}",
    "Status_Paused": "Paused",
    "Status_Filtered": "Auto Hidden",
    "Status_Active": "Active",
    "Status_AdminPending": "Admin mode applies after save and restart",
    "Settings_Title": "Settings",
    "Settings_ApplyHint": "*Click [Apply Changes] on the right after editing.",
    "Settings_Apply": "Apply Changes",
    "Basic_Title": "Basic Settings",
    "Basic_Language": "Display language",
    "Basic_MasterSwitch": "Enable click effects",
    "Basic_TrailSwitch": "Enable mouse trail",
    "Basic_ScrollbarVisibility": "Scrollbar visibility",
    "Basic_ScrollbarAlways": "Always visible",
    "Basic_ScrollbarOnScroll": "While scrolling only",
    "Basic_ScrollbarHint": "* Uses a thinner scrollbar. Showing it only while scrolling reduces flicker when resizing the panel or switching tabs.",
    "Basic_ClickType": "Trigger buttons",
    "Basic_LeftClick": "Left only",
    "Basic_RightClick": "Right only",
    "Basic_BothClick": "Both",
    "Basic_MiddleClick": "Trigger on middle click",
    "Basic_ScreenshotMode": "Screenshot compatibility",
    "Basic_ScreenshotHint": "* (Experimental) Hides overlay briefly during screenshots or QQ screenshot hotkeys.",
    "Basic_AutoStart": "Start with Windows",
    "Basic_StartSilent": "Start silently (tray only)",
    "Basic_RunAsAdmin": "Run as administrator",
    "Basic_RunAsAdminHint": "* Required for effects over elevated windows such as Task Manager.",
    "Basic_Touchscreen": "Touchscreen mode",
    "Basic_TouchscreenHint": "* Effects work when the cursor is hidden; for touchscreens or certain fullscreen apps.",
    "Basic_Telemetry": "Send anonymous usage data to improve the app",
    "Visual_Title": "Visual",
    "Visual_ResetDefaults": "Restore defaults",
    "Visual_InputHint": "Tip: click a number, edit, then press Enter",
    "Visual_Scale": "Scale",
    "Visual_Opacity": "Global opacity",
    "Visual_LinkedSpeed": "Use same animation speed for trail and click",
    "Visual_LinkedSpeedHint": "When off, trail and click speeds are independent of trail refresh rate below.",
    "Visual_AnimSpeed": "Animation speed",
    "Visual_TrailAnimSpeed": "Trail animation speed",
    "Visual_ClickAnimSpeed": "Click animation speed",
    "Visual_TrailRefresh": "Trail refresh rate",
    "Visual_Color": "Effect color",
    "Visual_ChangeColor": "Change color",
    "Filter_Title": "Environment Filter",
    "Filter_Enable": "Enable smart environment detection",
    "Filter_Fullscreen": "Pause when a fullscreen app is in foreground",
    "Filter_Desktop": "Show effects on desktop",
    "Filter_Profiles": "Profile management",
    "Filter_Delete": "Delete",
    "Filter_Rename": "Rename",
    "Filter_New": "New",
    "Filter_Mode": "Filter mode",
    "Filter_Mode_Disabled": "🚫 Off",
    "Filter_Mode_Blacklist": "❌ Blacklist",
    "Filter_Mode_Whitelist": "✅ Whitelist",
    "Filter_ProcessList": "Configured processes",
    "Filter_Remove": "Remove",
    "Filter_AddProcess": "Add process",
    "Filter_Add": "Add",
    "Filter_Browse": "Browse...",
    "Filter_SelectRunning": "From running",
    "MultiScreen_Title": "Multi-display",
    "MultiScreen_Refresh": "Refresh displays",
    "MultiScreen_Hint": "Select displays for effect windows. Settings are remembered by display name and hardware ID.",
    "MultiScreen_Enable": "Enable",
    "MultiScreen_Primary": " (Primary)",
    "MultiScreen_Scale": "Scale {0}%",
    "MultiScreen_Detail": "{0}  ·  Position ({1}, {2})  ·  {3}",
    "About_Title": "About",
    "About_CheckUpdate": "Check for updates",
    "About_CheckingUpdate": "Checking...",
    "About_Description": "Blue Archive–style mouse click effects for Windows",
    "About_SecurityWarning": "Download only from official sources. Unofficial builds may be unsafe or tampered with.",
    "About_Support": "If you enjoy BASpark, consider supporting development ☕",
    "About_OfficialSite": "🌐 Official website",
    "About_Github": "🌐 GitHub repository",
    "About_Bilibili": "📺 Bilibili",
    "About_QQ": "💬 QQ group",
    "About_Sponsor": "☕ Sponsor the author",
    "About_Discord": "💬 Join Discord",
    "About_DevOptions": "Developer options",
    "About_ResetAll": "Reset all settings and exit",
    "Overlay_RunningProcess": "Add from running processes",
    "Overlay_Cancel": "Cancel",
    "Overlay_ConfirmAdd": "Add selected",
    "Overlay_VisualReset": "Restore visual defaults",
    "Overlay_ConfirmReset": "Restore",
    "Overlay_RenameProfile": "Rename profile",
    "Overlay_RenamePrompt": "Enter a new profile name:",
    "Overlay_ConfirmRename": "Confirm",
    "Msg_UpdateAvailable": "New version V{0}\n\nChanges:\n{1}\n\nDownload now?",
    "Msg_UpdateAvailable_Title": "Update available",
    "Msg_UpToDate": "You are on the latest version.",
    "Msg_CheckUpdate_Title": "Check for updates",
    "Msg_CheckUpdateFailed": "Update check failed:\n{0}",
    "Msg_NetworkError": "Network error",
    "Msg_NoUpdateNotes": "No release notes",
    "Msg_DefaultNoticeTitle": "Announcement",
    "Msg_OpenLinkFailed": "Could not open link: {0}",
    "Msg_KeepOneProfile": "At least one profile is required.",
    "Msg_Info": "Notice",
    "Msg_ConfirmDeleteProfile": "Delete '{0}'?",
    "Msg_ConfirmDelete_Title": "Confirm delete",
    "Msg_SelectVisualReset": "Select at least one item to restore.",
    "Msg_VisualReset_Title": "Restore defaults",
    "Msg_VisualResetDone": "Selected visual settings were restored and saved.",
    "Msg_MinOneScreen": "At least one display must be enabled.",
    "Msg_MultiScreen_Title": "Multi-display",
    "Msg_AdminRestart": "Restart as administrator to apply this setting?",
    "Msg_AdminRestart_Title": "Elevation required",
    "Msg_SettingsApplied": "Settings applied successfully!",
    "Msg_RestartAdminFailed": "Failed to restart elevated. Right-click the app and run as administrator.\n{0}",
    "Msg_Error": "Error",
    "Msg_ConfirmReset": "Reset all settings? The app will close.",
    "Msg_ConfirmReset_Title": "Confirm reset",
    "Msg_DeleteFailed": "Delete failed: {0}",
    "Msg_LanguageRestart": "Language changed. Restart now to apply all UI text?",
    "Msg_LanguageRestart_Title": "Language changed",
    "Dialog_ExeFilter": "Executables (*.exe)|*.exe",
    "Dialog_SelectProcess": "Select process",
    "Profile_Default": "Default",
    "Profile_New": "New profile",
    "Profile_NewNumbered": "New profile {0}",
    "VisualReset_Scale": "Scale",
    "VisualReset_Scale_Sub": "Default 1.50 ×",
    "VisualReset_Opacity": "Global opacity",
    "VisualReset_Opacity_Sub": "Default 100 %",
    "VisualReset_UnifiedSpeed": "Unified animation speed",
    "VisualReset_UnifiedSpeed_Sub": "Linked speed, default 1.00 ×",
    "VisualReset_TrailSpeed": "Trail animation speed",
    "VisualReset_TrailSpeed_Sub": "Default 1.00 ×",
    "VisualReset_ClickSpeed": "Click animation speed",
    "VisualReset_ClickSpeed_Sub": "Default 1.00 ×",
    "VisualReset_TrailRefresh": "Trail refresh rate",
    "VisualReset_TrailRefresh_Sub": "Default 40 Hz",
    "VisualReset_Color": "Effect color",
    "VisualReset_Color_Sub": "Default RGB(45,175,255)",
    "Version_ReadFailed": "Failed to read version",
})

ja = dict(en)
ja.update({
    "App_Title_ControlPanel": "BASpark - コントロールパネル",
    "App_AlreadyRunning": "BASpark は既に実行中です。システムトレイを確認してください。",
    "App_AlreadyRunning_Title": "お知らせ",
    "Tray_Text": "BASpark - クリックエフェクト",
    "Tray_OpenPanel": "コントロールパネルを開く",
    "Tray_Restart": "アプリを再起動",
    "Tray_Exit": "完全に終了",
    "Tray_RestartFailed": "再起動に失敗しました: {0}",
    "WebView2_InitFailed": "WebView2 の初期化に失敗しました: {0}",
    "LangSelect_Title": "言語を選択",
    "LangSelect_Subtitle": "表示言語を選択してください。後から設定で変更できます。",
    "LangSelect_Continue": "続行",
    "Privacy_Title": "BASpark へようこそ",
    "Privacy_Intro": "ご利用前に以下の内容をお読みください：",
    "Privacy_OpenSource_Title": "● オープンソース",
    "Privacy_OpenSource_Body": "本ソフトは無料のオープンソースです。転売は禁止です。有料で入手した場合はプラットフォームに通報し返金を請求してください。",
    "Privacy_Security_Title": "● セキュリティ警告（重要）",
    "Privacy_Security_Body": "必ず公式チャネルからダウンロードしてください。第三者配布版は改ざんやマルウェアの可能性があります。",
    "Privacy_Privacy_Title": "● プライバシー",
    "Privacy_Privacy_Body": "キー入力・ファイル・個人情報は収集しません。エフェクトはすべてローカルで描画されます。",
    "Privacy_Telemetry": "匿名の利用統計で改善に協力する",
    "Privacy_Refuse": "拒否して終了",
    "Privacy_Agree": "同意して続行",
    "Privacy_Tagline": "Sensei, welcome back to Schale.",
    "Privacy_VersionFailed": "バージョン情報の取得に失敗",
    "Nav_Home": "ホーム",
    "Nav_Settings": "設定",
    "Nav_Basic": "基本設定",
    "Nav_Visual": "ビジュアル",
    "Nav_Filter": "環境フィルター",
    "Nav_MultiScreen": "マルチディスプレイ",
    "Nav_About": "情報",
    "Welcome_NoticeLoading": "読み込み中...",
    "Welcome_Title": "おかえりなさい、先生！",
    "Welcome_Subtitle": "Sensei, welcome back!",
    "Welcome_StatsTitle": "リアルタイム統計",
    "Welcome_StatusLabel": "状態:",
    "Welcome_ClicksLabel": "累計クリック数:",
    "Welcome_ClicksUnit": "{0} 回",
    "Status_Paused": "一時停止",
    "Status_Filtered": "環境フィルター中",
    "Status_Active": "動作中",
    "Status_AdminPending": "管理者モードは保存後の再起動で有効になります",
    "Settings_Title": "設定",
    "Settings_ApplyHint": "*変更後は右の [変更を適用] をクリックしてください。",
    "Settings_Apply": "変更を適用",
    "Basic_Title": "基本設定",
    "Basic_Language": "表示言語",
    "Basic_MasterSwitch": "クリックエフェクトを有効にする",
    "Basic_TrailSwitch": "マウスの常時トレイルを有効にする",
    "Basic_ScrollbarVisibility": "スクロールバーの表示",
    "Basic_ScrollbarAlways": "常に表示",
    "Basic_ScrollbarOnScroll": "スクロール時のみ",
    "Basic_ScrollbarHint": "* 細いスクロールバーを使用します。スクロール時のみ表示にすると、ウィンドウサイズ変更やタブ切替時の表示/非表示のちらつきを抑えられます。",
    "Basic_ClickType": "トリガーボタン",
    "Basic_LeftClick": "左のみ",
    "Basic_RightClick": "右のみ",
    "Basic_BothClick": "左右",
    "Basic_MiddleClick": "中クリックでトリガー",
    "Basic_ScreenshotMode": "スクリーンショット互換",
    "Basic_ScreenshotHint": "*（実験的）スクリーンショットや QQ の既定ショートカット検出時にオーバーレイを一時非表示にします。",
    "Basic_AutoStart": "Windows 起動時に実行",
    "Basic_StartSilent": "サイレント起動（トレイのみ）",
    "Basic_RunAsAdmin": "管理者として実行",
    "Basic_RunAsAdminHint": "* タスクマネージャーなどの高権限ウィンドウでエフェクトを表示する場合に必要です。",
    "Basic_Touchscreen": "タッチスクリーンモード",
    "Basic_TouchscreenHint": "* カーソル非表示時もエフェクトが動作します。タッチスクリーンや特定の全画面アプリ向けです。",
    "Basic_Telemetry": "匿名の利用データの送信を許可",
    "Visual_Title": "ビジュアル",
    "Visual_ResetDefaults": "既定値に戻す",
    "Visual_InputHint": "ヒント: 数値をクリックして編集し Enter で適用",
    "Visual_Scale": "拡大率",
    "Visual_Opacity": "全体の不透明度",
    "Visual_LinkedSpeed": "トレイルとクリックで同じアニメ速度を使用",
    "Visual_LinkedSpeedHint": "オフにするとトレイルとクリックの速度を個別に設定できます（下の更新率とは別）。",
    "Visual_AnimSpeed": "アニメーション速度",
    "Visual_TrailAnimSpeed": "トレイルのアニメ速度",
    "Visual_ClickAnimSpeed": "クリックのアニメ速度",
    "Visual_TrailRefresh": "トレイル更新率",
    "Visual_Color": "エフェクト色",
    "Visual_ChangeColor": "色を変更",
    "Filter_Title": "環境フィルター",
    "Filter_Enable": "スマート環境検出を有効にする",
    "Filter_Fullscreen": "全画面アプリが前面のとき自動一時停止",
    "Filter_Desktop": "デスクトップでエフェクトを表示",
    "Filter_Profiles": "プロファイル管理",
    "Filter_Delete": "削除",
    "Filter_Rename": "名前変更",
    "Filter_New": "新規",
    "Filter_Mode": "フィルターモード",
    "Filter_Mode_Disabled": "🚫 オフ",
    "Filter_Mode_Blacklist": "❌ ブラックリスト",
    "Filter_Mode_Whitelist": "✅ ホワイトリスト",
    "Filter_ProcessList": "設定済みプロセス",
    "Filter_Remove": "削除",
    "Filter_AddProcess": "プロセスを追加",
    "Filter_Add": "追加",
    "Filter_Browse": "参照...",
    "Filter_SelectRunning": "実行中から選択",
    "MultiScreen_Title": "マルチディスプレイ",
    "MultiScreen_Refresh": "ディスプレイを更新",
    "MultiScreen_Hint": "エフェクトを表示するディスプレイを選択します。名前とハードウェア ID で記憶します。",
    "MultiScreen_Enable": "有効",
    "MultiScreen_Primary": " (プライマリ)",
    "MultiScreen_Scale": "拡大 {0}%",
    "MultiScreen_Detail": "{0}  ·  位置 ({1}, {2})  ·  {3}",
    "About_Title": "情報",
    "About_CheckUpdate": "更新を確認",
    "About_CheckingUpdate": "確認中...",
    "About_Description": "『ブルーアーカイブ』風 UI のマウスクリックエフェクト",
    "About_SecurityWarning": "必ず公式チャネルからダウンロードしてください。非公式版は危険な場合があります。",
    "About_Support": "BASpark を気に入っていただけたら、開発の継続にご協力ください ☕",
    "About_OfficialSite": "🌐 公式サイト",
    "About_Github": "🌐 GitHub リポジトリ",
    "About_Bilibili": "📺 Bilibili",
    "About_QQ": "💬 QQ グループ",
    "About_Sponsor": "☕ 作者を支援",
    "About_Discord": "💬 Discord に参加",
    "About_DevOptions": "開発者向け",
    "About_ResetAll": "すべての設定をリセットして終了",
    "Overlay_RunningProcess": "実行中のプロセスから追加",
    "Overlay_Cancel": "キャンセル",
    "Overlay_ConfirmAdd": "追加を確定",
    "Overlay_VisualReset": "既定に戻すビジュアル項目を選択",
    "Overlay_ConfirmReset": "復元",
    "Overlay_RenameProfile": "プロファイルの名前変更",
    "Overlay_RenamePrompt": "新しいプロファイル名を入力:",
    "Overlay_ConfirmRename": "確定",
    "Msg_UpdateAvailable": "新しいバージョン V{0}\n\n変更内容:\n{1}\n\n今すぐダウンロードしますか？",
    "Msg_UpdateAvailable_Title": "更新があります",
    "Msg_UpToDate": "最新バージョンです。",
    "Msg_CheckUpdate_Title": "更新の確認",
    "Msg_CheckUpdateFailed": "更新の確認に失敗しました:\n{0}",
    "Msg_NetworkError": "ネットワークエラー",
    "Msg_NoUpdateNotes": "リリースノートなし",
    "Msg_DefaultNoticeTitle": "お知らせ",
    "Msg_OpenLinkFailed": "リンクを開けませんでした: {0}",
    "Msg_KeepOneProfile": "プロファイルは少なくとも 1 つ必要です。",
    "Msg_Info": "お知らせ",
    "Msg_ConfirmDeleteProfile": "「{0}」を削除しますか？",
    "Msg_ConfirmDelete_Title": "削除の確認",
    "Msg_SelectVisualReset": "復元する項目を 1 つ以上選択してください。",
    "Msg_VisualReset_Title": "既定値に戻す",
    "Msg_VisualResetDone": "選択したビジュアル設定を既定値に戻して保存しました。",
    "Msg_MinOneScreen": "少なくとも 1 つのディスプレイを有効にしてください。",
    "Msg_MultiScreen_Title": "マルチディスプレイ",
    "Msg_AdminRestart": "管理者として再起動して設定を適用しますか？",
    "Msg_AdminRestart_Title": "権限が必要です",
    "Msg_SettingsApplied": "設定を適用しました！",
    "Msg_RestartAdminFailed": "昇格再起動に失敗しました。右クリックで管理者として実行してください。\n{0}",
    "Msg_Error": "エラー",
    "Msg_ConfirmReset": "すべての設定をリセットしますか？アプリは終了します。",
    "Msg_ConfirmReset_Title": "リセットの確認",
    "Msg_DeleteFailed": "削除に失敗しました: {0}",
    "Msg_LanguageRestart": "言語を変更しました。すべての UI を反映するには再起動が必要です。今すぐ再起動しますか？",
    "Msg_LanguageRestart_Title": "言語を変更しました",
    "Dialog_ExeFilter": "実行ファイル (*.exe)|*.exe",
    "Dialog_SelectProcess": "プロセスを選択",
    "Profile_Default": "既定",
    "Profile_New": "新規プロファイル",
    "Profile_NewNumbered": "新規プロファイル {0}",
    "VisualReset_Scale": "拡大率",
    "VisualReset_Scale_Sub": "既定 1.50 ×",
    "VisualReset_Opacity": "全体の不透明度",
    "VisualReset_Opacity_Sub": "既定 100 %",
    "VisualReset_UnifiedSpeed": "統一アニメ速度",
    "VisualReset_UnifiedSpeed_Sub": "同一速度、既定 1.00 ×",
    "VisualReset_TrailSpeed": "トレイルのアニメ速度",
    "VisualReset_TrailSpeed_Sub": "既定 1.00 ×",
    "VisualReset_ClickSpeed": "クリックのアニメ速度",
    "VisualReset_ClickSpeed_Sub": "既定 1.00 ×",
    "VisualReset_TrailRefresh": "トレイル更新率",
    "VisualReset_TrailRefresh_Sub": "既定 40 Hz",
    "VisualReset_Color": "エフェクト色",
    "VisualReset_Color_Sub": "既定 RGB(45,175,255)",
    "Version_ReadFailed": "バージョン情報の取得に失敗",
})

if __name__ == "__main__":
    import os
    base = os.path.join(os.path.dirname(__file__), "..", "src", "Resources")
    write_resx(os.path.join(base, "Strings.resx"), zh)
    write_resx(os.path.join(base, "Strings.en.resx"), en)
    write_resx(os.path.join(base, "Strings.ja.resx"), ja)
    print("Generated", len(zh), "keys")
